
timezone: 'Europe/Berlin'

home:
  alias: /blog

pages:
  theme: antimatter
  order:
    by: header.time.start
    dir: asc
  dateformat:
    date: 'Y-m-dTH:i:sO'

cache:
  enabled: false
twig:
  cache: false                          # Set to true to enable twig caching

debugger:
  enabled: true                        # Enable Grav debugger and following settings
